# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('progress', models.IntegerField(default=0, null=True)),
                ('lasttime', models.DateField(blank=True, null=True)),
                ('nexttime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, null=True)),
                ('lasttime', models.DateField(blank=True, null=True)),
                ('nexttime', models.DateField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Card')),
            ],
        ),
    ]
