# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='lasttime',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nexttime',
        ),
        migrations.RemoveField(
            model_name='card',
            name='progress',
        ),
    ]
