# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20170412_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='bla', max_length=50),
            preserve_default=False,
        ),
    ]
