# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.CharField(default='Spartacus', max_length=50),
            preserve_default=False,
        ),
    ]
