# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_auto_20170415_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(through='reviewer.Progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
