# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='users',
        ),
    ]
