# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0011_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
