# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_auto_20170426_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewer.Category'),
        ),
        migrations.AlterField(
            model_name='card',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
