# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0014_auto_20170426_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='under_category',
            field=models.CharField(choices=[('SR', 'Strafrecht'), ('OR', 'Oeffentliches Recht'), ('ZR', 'Zivilrecht')], default='SR', max_length=2),
        ),
    ]
