# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0016_auto_20170426_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='lasttime',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
