# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0017_auto_20170429_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='lasttime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
