# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0018_auto_20170429_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 30, 20, 54, 2, 547463, tzinfo=utc), null=True),
        ),
    ]
