# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0019_auto_20170430_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 11, 16, 5, 39, 258102, tzinfo=utc), null=True),
        ),
    ]
