# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0020_auto_20170511_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='containing_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 11, 16, 6, 54, 719816, tzinfo=utc), null=True),
        ),
    ]
