# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0021_auto_20170511_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='containing_cards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 11, 17, 17, 19, 35187, tzinfo=utc), null=True),
        ),
    ]
