# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0022_auto_20170511_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='containing_cards',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='nexttime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
