# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0025_auto_20170522_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='solution',
            field=models.CharField(max_length=150),
        ),
    ]
