# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0026_auto_20170522_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution_ZR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.BooleanField(default=False)),
                ('p', models.BooleanField(default=False)),
                ('mangel', models.BooleanField(default=False)),
                ('p2', models.BooleanField(default=False)),
                ('gefahruebergang', models.BooleanField(default=False)),
                ('p3', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewer.Category'),
        ),
        migrations.AddField(
            model_name='solution_zr',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewer.Case'),
        ),
    ]
