# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0027_auto_20170522_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution_zr',
            name='solution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
