# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0028_auto_20170522_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_ZR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('explanation', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('solution', models.CharField(blank=True, max_length=150, null=True)),
                ('kv', models.BooleanField(default=False)),
                ('p', models.BooleanField(default=False)),
                ('mangel', models.BooleanField(default=False)),
                ('p2', models.BooleanField(default=False)),
                ('gefahruebergang', models.BooleanField(default=False)),
                ('p3', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewer.Category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='solution_zr',
            name='case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Solution_ZR',
        ),
    ]
